# ── Dotori App — DigitalOcean App Platform Spec ──
# 유료 계정 + GitHub Student Pack ($200 크레딧)
# Docs: https://docs.digitalocean.com/products/app-platform/reference/app-spec/
# Deploy: doctl apps create --spec .do/app.yaml
# Validate: doctl apps spec validate .do/app.yaml

name: dotori-app
region: sgp  # Singapore — 한국에서 가장 가까운 유효 DO 리전 (nrt은 미지원)

services:
  - name: web
    dockerfile_path: dotori-app/Dockerfile
    github:
      repo: QETTA/dotori-ver2
      branch: main
      deploy_on_push: false  # GitHub Actions ci.yml이 배포 담당 (이중 배포 방지)

    # source_dir 미설정 → 빌드 컨텍스트 = repo root
    # Dockerfile 내부에서 dotori-app/ 경로 참조

    instance_size_slug: apps-s-1vcpu-2gb
    instance_count: 1
    http_port: 3000

    routes:
      - path: /

    envs:
      # ── Auth ──
      - key: AUTH_SECRET
        type: SECRET
        scope: RUN_TIME
      - key: NEXTAUTH_URL
        value: ${APP_URL}
        type: GENERAL
        scope: RUN_TIME

      # ── Kakao OAuth ──
      - key: AUTH_KAKAO_ID
        type: SECRET
        scope: RUN_TIME
      - key: AUTH_KAKAO_SECRET
        type: SECRET
        scope: RUN_TIME

      # ── Kakao SDK (client-side, 빌드타임 주입) ──
      - key: NEXT_PUBLIC_KAKAO_JS_KEY
        type: GENERAL
        scope: BUILD_TIME
      - key: NEXT_PUBLIC_KAKAO_MAP_KEY
        type: GENERAL
        scope: BUILD_TIME
      - key: NEXT_PUBLIC_KAKAO_CHANNEL_ID
        type: GENERAL
        scope: BUILD_TIME
      - key: KAKAO_REST_API_KEY
        type: SECRET
        scope: RUN_TIME

      # ── MongoDB Atlas ──
      - key: MONGODB_URI
        type: SECRET
        scope: RUN_TIME
      - key: MONGODB_DB_NAME
        value: dotori
        type: GENERAL
        scope: RUN_TIME

      # ── AI ──
      - key: ANTHROPIC_API_KEY
        type: SECRET
        scope: RUN_TIME
      - key: AI_MODEL
        value: claude-sonnet-4-6
        type: GENERAL
        scope: RUN_TIME

      # ── Public Data APIs ──
      - key: PUBLIC_DATA_API_KEY
        type: SECRET
        scope: RUN_TIME
      - key: CHILDCARE_PORTAL_KEY
        type: SECRET
        scope: RUN_TIME

      # ── App ──
      - key: NODE_ENV
        value: production
        type: GENERAL
        scope: RUN_TIME
      - key: NEXT_PUBLIC_APP_URL
        value: ${APP_URL}
        type: GENERAL
        scope: BUILD_TIME
      - key: NEXT_PUBLIC_SITE_URL
        value: ${APP_URL}
        type: GENERAL
        scope: BUILD_TIME

      # ── Analytics ──
      - key: NEXT_PUBLIC_GA_ID
        type: GENERAL
        scope: BUILD_TIME

      # ── Cron ──
      - key: CRON_SECRET
        type: SECRET
        scope: RUN_TIME

      # ── 미래 기능 (활성화 시 주석 해제) ──
      # # Toss Payments (Phase 3)
      # - key: NEXT_PUBLIC_TOSS_CLIENT_KEY
      #   type: GENERAL
      #   scope: BUILD_TIME
      # # Sentry (Phase 4)
      # - key: NEXT_PUBLIC_SENTRY_DSN
      #   type: GENERAL
      #   scope: BUILD_TIME
      # - key: SENTRY_AUTH_TOKEN
      #   type: SECRET
      #   scope: BUILD_TIME
      # # Solapi Alimtalk (Phase 3)
      # - key: SOLAPI_API_KEY
      #   type: SECRET
      #   scope: RUN_TIME
      # - key: SOLAPI_API_SECRET
      #   type: SECRET
      #   scope: RUN_TIME
      # - key: KAKAO_SENDER_KEY
      #   type: SECRET
      #   scope: RUN_TIME

    health_check:
      http_path: /api/health
      initial_delay_seconds: 15
      period_seconds: 30
      timeout_seconds: 5
      failure_threshold: 5
      success_threshold: 1

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

# ── Custom domain (uncomment when ready) ──
# domains:
#   - domain: dotori.app
#     type: PRIMARY
#     minimum_tls_version: "1.3"
