# ── Dotori App — DigitalOcean App Platform Spec (v2 DOCR) ──
# Pre-built 이미지 배포: GHA에서 빌드 → DOCR push → DO pull (빌드 스킵)
# 유료 계정 + GitHub Student Pack ($200 크레딧)
#
# ── 최초 1회 셋업 ──
# doctl registry create dotori --region sgp --subscription-tier starter
# doctl apps update 29a6e4f6-b8ae-48b7-9ae3-3e3275b274c2 --spec .do/app.yaml
#
# Docs: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: dotori-app
region: sgp

services:
  - name: web
    # DOCR pre-built 이미지 (GHA CI에서 빌드+push)
    # DO는 이미지 pull만 → 배포 ~30초 (기존 Dockerfile 빌드 ~10분)
    image:
      registry_type: DOCR
      repository: web
      # CI deploy job replaces this to immutable tag: sha-<commit>
      tag: latest

    instance_size_slug: apps-s-1vcpu-2gb
    instance_count: 1
    http_port: 3000

    routes:
      - path: /

    envs:
      # ── Auth ──
      - key: AUTH_SECRET
        type: SECRET
        scope: RUN_TIME
      - key: NEXTAUTH_URL
        value: ${APP_URL}
        type: GENERAL
        scope: RUN_TIME

      # ── Kakao OAuth ──
      - key: AUTH_KAKAO_ID
        type: SECRET
        scope: RUN_TIME
      - key: AUTH_KAKAO_SECRET
        type: SECRET
        scope: RUN_TIME

      # ── Kakao SDK (서버사이드) ──
      - key: KAKAO_REST_API_KEY
        type: SECRET
        scope: RUN_TIME

      # ── MongoDB Atlas ──
      - key: MONGODB_URI
        type: SECRET
        scope: RUN_TIME
      - key: MONGODB_DB_NAME
        value: dotori
        type: GENERAL
        scope: RUN_TIME

      # ── AI ──
      - key: ANTHROPIC_API_KEY
        type: SECRET
        scope: RUN_TIME
      - key: AI_MODEL
        value: claude-sonnet-4-6
        type: GENERAL
        scope: RUN_TIME

      # ── Public Data APIs ──
      - key: PUBLIC_DATA_API_KEY
        type: SECRET
        scope: RUN_TIME
      - key: CHILDCARE_PORTAL_KEY
        type: SECRET
        scope: RUN_TIME

      # ── App ──
      - key: NODE_ENV
        value: production
        type: GENERAL
        scope: RUN_TIME

      # ── Cron ──
      - key: CRON_SECRET
        type: SECRET
        scope: RUN_TIME

      # ── NEXT_PUBLIC_* 는 Docker 빌드 시 주입됨 (GHA build-args) ──
      # BUILD_TIME scope 불필요 — 이미지에 이미 번들링

    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 1

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
