declare namespace NodeJS {
  interface ProcessEnv {
    readonly NEXT_PUBLIC_API_URL: string
    readonly NEXT_PUBLIC_KAKAO_KEY: string
    readonly NEXT_PUBLIC_KAKAO_MAP_KEY: string
    readonly NEXT_PUBLIC_E2E_DISABLE_EXTERNAL_SDK?: string
    readonly NEXT_PUBLIC_NAVER_KEY: string
    readonly NEXT_PUBLIC_TOSS_CLIENT_KEY: string
    readonly NEXT_PUBLIC_GA_ID: string
    readonly DATABASE_URL: string
    readonly MONGODB_URI?: string
    readonly OPENAI_API_KEY: string
    readonly OPENAI_API_URL: string
    readonly OPENAI_BASE_URL: string
    readonly OPENAI_HOST: string
    readonly OPENAI_MODEL: string
    readonly OPENAI_TEMPERATURE: string
    readonly OPENAI_TOP_P: string
    readonly OPENAI_MAX_TOKENS: string
    readonly OPENAI_EXTRA_BODY: string
    readonly OPENAI_REQUEST_TIMEOUT_MS: string
    readonly AI_PROVIDER: string
    readonly AI_BASE_URL: string
    readonly AI_MODEL: string
    readonly SPARK_API_KEY: string
    readonly SPARK_API_URL: string
    readonly SPARK_API_HOST: string
    readonly SPARK_BASE_URL: string
    readonly SPARK_MODEL: string
    readonly SPARK_TEMPERATURE: string
    readonly SPARK_TOP_P: string
    readonly SPARK_MAX_TOKENS: string
    readonly SPARK_REASONING: string
    readonly SPARK_EXTRA_BODY: string
    readonly SPARK_REQUEST_TIMEOUT_MS: string
    readonly SPARK_SYSTEM_PROMPT: string
    readonly JWT_SECRET: string
    readonly KAKAO_CLIENT_SECRET: string
    readonly NAVER_CLIENT_SECRET: string
    readonly NEXT_PUBLIC_KAKAO_CHANNEL_PUBLIC_ID: string
    readonly NEXT_PUBLIC_KAKAO_SDK_VERSION: string
    readonly NEXT_PUBLIC_KAKAO_PIXEL_ID: string
    readonly NEXT_PUBLIC_APP_URL: string
  }
}
