/* ═══════════════════════════════════════
 * 도토리 — Mock Data Repository
 * Single source of truth for demo/dev
 * ═══════════════════════════════════════ */

export const MOCK_FACILITIES = [
  {
    id: 'f1',
    name: '해맑은 어린이집',
    type: '민간',
    address: '서울 강남구 역삼동 123-4',
    distance: '820m',
    rating: 4.5,
    reviewCount: 23,
    probability: 72,
    phone: '02-1234-5678',
    openHours: '07:30 - 19:30',
    established: '2018.03',
    director: '김미영',
    capacity: 20,
    enrolled: 19,
    ageGroups: [
      { label: '0세반', capacity: 6, enrolled: 6, waiting: 8 },
      { label: '1세반', capacity: 7, enrolled: 7, waiting: 5 },
      { label: '2세반', capacity: 7, enrolled: 6, waiting: 3 },
    ],
    features: ['실시간 CCTV', '통학차량', '영양사 상주', '연장 보육', '장애아 통합반'],
    factors: [
      { label: '대기순번', value: '#3', impact: 'positive' as const },
      { label: '정원 대비 대기', value: '8/6명', impact: 'negative' as const },
      { label: '최근 TO 빈도', value: '월 1.2건', impact: 'positive' as const },
      { label: '지역 경쟁률', value: '3.2:1', impact: 'neutral' as const },
    ],
    forecast: [
      { month: '3월', prob: 58, toExpected: 1 },
      { month: '4월', prob: 65, toExpected: 1 },
      { month: '5월', prob: 72, toExpected: 2 },
      { month: '6월', prob: 78, toExpected: 2 },
    ],
    reviews: [
      {
        id: 'r1',
        author: '지○ 엄마',
        date: '2026.02.01',
        rating: 5,
        text: '선생님들이 정말 따뜻하시고 아이가 매일 가고 싶어해요. 급식도 맛있고 깨끗합니다.',
        tags: ['친절한 선생님', '맛있는 급식'],
      },
      {
        id: 'r2',
        author: '수○ 엄마',
        date: '2026.01.15',
        rating: 4,
        text: '시설이 깨끗하고 프로그램이 다양해요. 다만 주차가 좀 불편합니다.',
        tags: ['깨끗한 시설', '다양한 프로그램'],
      },
      {
        id: 'r3',
        author: '하○ 엄마',
        date: '2025.12.20',
        rating: 5,
        text: '원장님이 교육에 대한 철학이 확실하시고, CCTV도 실시간으로 볼 수 있어 안심이에요.',
        tags: ['교육 철학', 'CCTV'],
      },
    ],
    monthlyCost: 350000,
    extensionCare: true,
    bus: true,
    cctv: true,
    nutritionist: true,
  },
  {
    id: 'f2',
    name: '무지개 어린이집',
    type: '국공립',
    address: '서울 서초구 서초동 456-7',
    distance: '1.2km',
    rating: 4.2,
    reviewCount: 45,
    probability: 45,
    phone: '02-2345-6789',
    openHours: '07:30 - 19:30',
    established: '2015.09',
    director: '박선미',
    capacity: 30,
    enrolled: 28,
    ageGroups: [
      { label: '0세반', capacity: 9, enrolled: 9, waiting: 12 },
      { label: '1세반', capacity: 10, enrolled: 10, waiting: 8 },
      { label: '2세반', capacity: 11, enrolled: 9, waiting: 5 },
    ],
    features: ['실시간 CCTV', '영양사 상주', '연장 보육', '텃밭 체험'],
    factors: [
      { label: '대기순번', value: '#8', impact: 'negative' as const },
      { label: '정원 대비 대기', value: '12/9명', impact: 'negative' as const },
      { label: '최근 TO 빈도', value: '월 0.8건', impact: 'neutral' as const },
      { label: '지역 경쟁률', value: '4.5:1', impact: 'negative' as const },
    ],
    forecast: [
      { month: '3월', prob: 35, toExpected: 1 },
      { month: '4월', prob: 42, toExpected: 1 },
      { month: '5월', prob: 45, toExpected: 1 },
      { month: '6월', prob: 51, toExpected: 2 },
    ],
    reviews: [
      {
        id: 'r4',
        author: '민○ 엄마',
        date: '2026.01.28',
        rating: 4,
        text: '국공립이라 비용이 저렴하고 관리가 체계적이에요.',
        tags: ['합리적 비용', '체계적 관리'],
      },
      {
        id: 'r5',
        author: '현○ 엄마',
        date: '2026.01.10',
        rating: 5,
        text: '텃밭 체험이 정말 좋아요. 아이가 자연과 친해졌어요.',
        tags: ['자연 체험', '특별 프로그램'],
      },
    ],
    monthlyCost: 250000,
    extensionCare: true,
    bus: false,
    cctv: true,
    nutritionist: true,
  },
  {
    id: 'f3',
    name: '햇살 어린이집',
    type: '민간',
    address: '서울 강남구 삼성동 789-1',
    distance: '650m',
    rating: 4.7,
    reviewCount: 31,
    probability: 88,
    phone: '02-3456-7890',
    openHours: '07:00 - 20:00',
    established: '2020.01',
    director: '이정수',
    capacity: 15,
    enrolled: 13,
    ageGroups: [
      { label: '0세반', capacity: 5, enrolled: 4, waiting: 3 },
      { label: '1세반', capacity: 5, enrolled: 5, waiting: 3 },
      { label: '2세반', capacity: 5, enrolled: 4, waiting: 2 },
    ],
    features: ['실시간 CCTV', '통학차량', '영양사 상주', '연장 보육', '영어 프로그램', '숲 체험'],
    factors: [
      { label: '대기순번', value: '#1', impact: 'positive' as const },
      { label: '정원 대비 대기', value: '3/5명', impact: 'positive' as const },
      { label: '최근 TO 빈도', value: '월 1.8건', impact: 'positive' as const },
      { label: '지역 경쟁률', value: '1.8:1', impact: 'positive' as const },
    ],
    forecast: [
      { month: '3월', prob: 82, toExpected: 2 },
      { month: '4월', prob: 85, toExpected: 2 },
      { month: '5월', prob: 88, toExpected: 3 },
      { month: '6월', prob: 92, toExpected: 3 },
    ],
    reviews: [
      {
        id: 'r6',
        author: '은○ 엄마',
        date: '2026.02.10',
        rating: 5,
        text: '최신 시설에 선생님들도 젊고 열정적이에요. 영어 수업도 재미있어요.',
        tags: ['최신 시설', '영어 수업'],
      },
      {
        id: 'r7',
        author: '준○ 엄마',
        date: '2026.01.25',
        rating: 5,
        text: '숲 체험을 매주 가는데 아이가 너무 좋아해요.',
        tags: ['숲 체험', '야외 활동'],
      },
      {
        id: 'r8',
        author: '서○ 엄마',
        date: '2026.01.05',
        rating: 4,
        text: '전반적으로 만족합니다. 다만 비용이 조금 높은 편이에요.',
        tags: ['높은 만족도'],
      },
    ],
    monthlyCost: 450000,
    extensionCare: true,
    bus: true,
    cctv: true,
    nutritionist: true,
  },
]

export const MOCK_ALERTS = [
  {
    id: 'a1',
    facilityId: 'f1',
    facilityName: '해맑은 어린이집',
    ageGroup: '0세반',
    toCount: 1,
    probability: 72,
    reason: '재원 아동 1명이 타 시설로 이동하여 TO가 발생했습니다.',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    isRead: false,
  },
  {
    id: 'a2',
    facilityId: 'f3',
    facilityName: '햇살 어린이집',
    ageGroup: '1세반',
    toCount: 2,
    probability: 88,
    reason: '3월 학급 재편성으로 인한 정원 변동입니다.',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    isRead: false,
  },
  {
    id: 'a3',
    facilityId: 'f2',
    facilityName: '무지개 어린이집',
    ageGroup: '2세반',
    toCount: 1,
    probability: 45,
    reason: '원아 전출로 인한 결원 발생.',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    isRead: true,
  },
  {
    id: 'a4',
    facilityId: 'f1',
    facilityName: '해맑은 어린이집',
    ageGroup: '1세반',
    toCount: 1,
    probability: 65,
    reason: '담당 교사 추가 채용으로 정원이 확대되었습니다.',
    timestamp: new Date(Date.now() - 172800000).toISOString(),
    isRead: true,
  },
  {
    id: 'a5',
    facilityId: 'f3',
    facilityName: '햇살 어린이집',
    ageGroup: '0세반',
    toCount: 1,
    probability: 88,
    reason: '원아 가정 이사로 인한 퇴원.',
    timestamp: new Date(Date.now() - 345600000).toISOString(),
    isRead: true,
  },
  {
    id: 'a6',
    facilityId: 'f2',
    facilityName: '무지개 어린이집',
    ageGroup: '0세반',
    toCount: 1,
    probability: 42,
    reason: '연초 정기 TO 발생.',
    timestamp: new Date(Date.now() - 604800000).toISOString(),
    isRead: true,
  },
]

export const MOCK_USER = {
  id: 'u1',
  name: '민지 엄마',
  email: 'minji.mom@email.com',
  plan: 'pro' as const,
  planExpiresAt: '2026-03-15T00:00:00Z',
  children: [{ id: 'c1', name: '민지', birthYear: 2024, birthMonth: 6, gender: 'female' as const }],
  preferences: {
    district: '강남구',
    maxDistance: '1km',
    facilityTypes: ['민간', '국공립'],
    priorities: ['distance', 'safety', 'meal'],
  },
  createdAt: '2026-01-15T00:00:00Z',
}

/* ─── Helper to get facility by ID ─── */
export function getFacilityById(id: string) {
  return MOCK_FACILITIES.find((f) => f.id === id) || MOCK_FACILITIES[0]
}
