export const BRAND = {
	symbol: "/brand/dotori-symbol.svg",
	symbolCorporate: "/brand/dotori-symbol-corporate.svg",
	symbolMonoDark: "/brand/dotori-symbol-mono-dark.svg",
	symbolMonoWhite: "/brand/dotori-symbol-mono-white.svg",
	lockupHorizontal: "/brand/dotori-lockup-horizontal.svg",
	lockupHorizontalKr: "/brand/dotori-lockup-horizontal-kr.svg",
	lockupCorporate: "/brand/dotori-lockup-corporate.svg",
	lockupStacked: "/brand/dotori-lockup-stacked.svg",
	lockupStackedCorp: "/brand/dotori-lockup-stacked-corporate.svg",
	appIconWarm: "/brand/dotori-app-icon-warm.svg",
	appIconDark: "/brand/dotori-app-icon-dark.svg",
	appIconSimple: "/brand/dotori-app-icon-simplified.svg",
	favicon: "/brand/dotori-favicon.svg",
	ogImage: "/brand/dotori-og-image.svg",
	socialGradient: "/brand/dotori-social-profile-gradient.svg",
	socialCream: "/brand/dotori-social-profile-cream.svg",
	emailSignature: "/brand/dotori-email-signature.svg",
	watermark: "/brand/dotori-watermark.svg",
	emptyState: "/brand/dotori-empty-state.svg",
	errorState: "/brand/dotori-error-state.svg",
} as const;
